### ISSUE TITLE
SDK升级到4.16.1后初始化报错！No implementation found for int com.ez.stream.NativeApi.initSDK(int) (tried Java_com_ez_stream_NativeApi_initSDK and Java_com_ez_stream_NativeApi_initSDK__I)

### ISSUE THREAD

**Issue by dongjianxiong** [Ezviz-Open/EzvizSDK-Android#9]
V/u: class com.kingsoft.iothotel.bean.ez.EZVideoTokenBean
I/LocalInfo: getDataWithAesCompatibleToOldVersions, key is: user_name
I/LocalInfo: getDataWithAesCompatibleToOldVersions, key is: hardwareCode
I/LocalInfo: getDataWithAesCompatibleToOldVersions, key is: EZAccessToken_JSON
E/ft.iothotel.de: No implementation found for int com.ez.stream.NativeApi.initSDK(int) (tried Java_com_ez_stream_NativeApi_initSDK and Java_com_ez_stream_NativeApi_initSDK__I)
D/AndroidRuntime: Shutting down VM
I/QarthLog: [PatchStore] createDisableExceptionQarthFile
    [PatchStore] create disable file for com.kingsoft.iothotel.dev uid is 10464
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kingsoft.iothotel.dev, PID: 28078
    java.lang.UnsatisfiedLinkError: No implementation found for int com.ez.stream.NativeApi.initSDK(int) (tried Java_com_ez_stream_NativeApi_initSDK and Java_com_ez_stream_NativeApi_initSDK__I)
        at com.ez.stream.NativeApi.initSDK(Native Method)
        at com.ez.stream.NativeApi.a(NativeApi.java:51)
        at com.ez.stream.EZStreamClientManager.g(EZStreamClientManager.java:109)
        at com.ez.stream.EZStreamClientManager.e(EZStreamClientManager.java:94)
        at com.videogo.main.AppManager.<init>(AppManager.java:251)
        at com.videogo.main.AppManager.getInstance(AppManager.java:110)
        at com.videogo.openapi.EzvizAPI.<init>(EzvizAPI.java:366)
        at com.videogo.openapi.EzvizAPI.init(EzvizAPI.java:406)
        at com.videogo.openapi.EZOpenSDK.initLib(EZOpenSDK.java:104)
        at d.j.b.f.b.b(EZAccessBridge.java:71)
        at d.j.b.h.c.d.k.e.d.c.e.b.q(EzApConfigViewModel.java:98)
        at d.j.b.h.c.d.k.e.d.c.e.b.k(EzApConfigViewModel.java:30)
        at d.j.b.h.c.d.k.e.d.c.e.b$a$a.run(EzApConfigViewModel.java:72)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
D/JIGUANG-JCommon: [JCommonInterface] onEvent action:deviceinfo
E/libc: Access denied finding property "vendor.cellular.ril.imsi"
W/jg_fr_pool_thre: type=1400 audit(0.0:87861): avc: denied { read } for pid=28078 name="u:object_r:vendor_default_prop:s0" dev="tmpfs" ino=3071 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:vendor_default_prop:s0 tclass=file permissive=0
E/ft.iothotel.de: No implementation found for void com.bun.lib.a.a(boolean) (tried Java_com_bun_lib_a_a and Java_com_bun_lib_a_a__Z)
D/CertUpdateHelper: ["https://download.hikops.com/cert/Entrust_CA.pem.cer","https://download.hikops.com/cert/global_ca.cer"]
D/CertUpdateHelper: download https://download.hikops.com/cert/Entrust_CA.pem.cer
    download https://download.hikops.com/cert/Entrust_CA.pem.cer exists
    download https://download.hikops.com/cert/global_ca.cer
D/CertUpdateHelper: download https://download.hikops.com/cert/global_ca.cer exists
E/CrashReport: Java Crash Happen cause by main(1)
W/CrashReport: no read_log permission!
I/CrashReport: user log size:0
E/CrashReport: stack frame :20, has cause false
E/CrashReport: #++++++++++Record By Bugly++++++++++#
E/CrashReport: # You can use Bugly(http:\\bugly.qq.com) to get more Crash Detail!
    # PKG NAME: com.kingsoft.iothotel.dev
    # APP VER: 3.2.6
    # SDK VER: 3.3.3-3.7.5
E/CrashReport: # LAUNCH TIME: 2021-05-24 16:41:55
    # CRASH TYPE: JAVA_CRASH
    # CRASH TIME: 2021-05-24 16:42:59
    # CRASH PROCESS: com.kingsoft.iothotel.dev
E/CrashReport: # CRASH THREAD: main
    # REPORT ID: 8efa5397-6e16-41bf-a95c-65a9f51b6b09
    # CRASH DEVICE: TAS-AN00 UNROOT
E/CrashReport: # RUNTIME AVAIL RAM:3735523328 ROM:87144902656 SD:87123931136
E/CrashReport: # RUNTIME TOTAL RAM:7772237824 ROM:117430026240 SD:117409054720
    # CRASH STACK: 
    java.lang.UnsatisfiedLinkError: No implementation found for int com.ez.stream.NativeApi.initSDK(int) (tried Java_com_ez_stream_NativeApi_initSDK and Java_com_ez_stream_NativeApi_initSDK__I)
        at com.ez.stream.NativeApi.initSDK(Native Method)
        at com.ez.stream.NativeApi.a(NativeApi.java:51)
        at com.ez.stream.EZStreamClientManager.g(EZStreamClientManager.java:109)
        at com.ez.stream.EZStreamClientManager.e(EZStreamClientManager.java:94)
        at com.videogo.main.AppManager.<init>(AppManager.java:251)
        at com.videogo.main.AppManager.getInstance(AppManager.java:110)
        at com.videogo.openapi.EzvizAPI.<init>(EzvizAPI.java:366)
        at com.videogo.openapi.EzvizAPI.init(EzvizAPI.java:406)
        at com.videogo.openapi.EZOpenSDK.initLib(EZOpenSDK.java:104)
        at d.j.b.f.b.b(EZAccessBridge.java:71)
        at d.j.b.h.c.d.k.e.d.c.e.b.q(EzApConfigViewModel.java:98)
        at d.j.b.h.c.d.k.e.d.c.e.b.k(EzApConfigViewModel.java:30)
        at d.j.b.h.c.d.k.e.d.c.e.b$a$a.run(EzApConfigViewModel.java:72)
        at android.os.Handler.handleCallback(Handler.java:900)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8393)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
    #++++++++++++++++++++++++++++++++++++++++++#
D/CrashReport: [Database] deleted t_lr data 1
D/CrashReport: [Database] insert t_lr success.
I/CrashReportInfo: [crash] a crash occur, handling...
D/CrashReport: [Database] insert t_cr success.
D/CrashReport: insert t_cr success!
I/CrashReportInfo: [crash] save crash success
I/CrashReport: try to upload right now
D/CrashReport: libInfo null
    attach pageTracingList
D/CrashReport: java.lang.UnsatisfiedLinkError rid:8efa5397-6e16-41bf-a95c-65a9f51b6b09 sess:69d78cf7-7212-43a2-ba3f-99f4673f4ca1 ls:63s isR:false isF:true isM:false isN:false mc:0 ,null ,isUp:false ,vm:29
D/CrashReport: [UploadManager] Add upload task (pid=28078 | tid=28078)
D/CrashReport: [UploadManager] Execute synchronized upload task (pid=28078 | tid=28078)
D/CrashReport: [Upload] Run upload task with cmd: 830
D/CrashReport: [Util] Zip 29944 bytes data with type Gzip
D/CrashReport: [Database] deleted t_lr data 1
D/CrashReport: [Database] insert t_lr success.
D/CrashReport: [UploadManager] Uploading(ID:1004) time: 2021-05-24 16:42:59
    [Upload] Send 3688 bytes

**Comment by Ezviz-Open** [comment]
SDK内部已做调整，SDK更新到v4.19.8.1版本即可。
